global:
  scrape_interval:     1s 
  evaluation_interval: 1s 

scrape_configs:
  - job_name: 'gnmic'
    scrape_interval: 1s 
    consul_sd_configs:
      - server: clab-telemetry-consul-agent:8500
        services:
          - prometheus-prom-output
