{
 "title": "OSPF",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "OSPF graph",
   "type": "agenty-flowcharting-panel",
   "gridPos": { "h": 22, "w": 12, "x": 0, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "network_instance_protocols_ospf_instance_admin_state{target=\"clab-telemetry-R11\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "network_instance_protocols_ospf_instance_admin_state{target=\"clab-telemetry-R12\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "network_instance_protocols_ospf_instance_admin_state{target=\"clab-telemetry-R13\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "network_instance_protocols_ospf_instance_admin_state{target=\"clab-telemetry-R14\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "network_instance_protocols_ospf_instance_router_id{target=\"clab-telemetry-R11\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "network_instance_protocols_ospf_instance_router_id{target=\"clab-telemetry-R12\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "network_instance_protocols_ospf_instance_router_id{target=\"clab-telemetry-R13\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "network_instance_protocols_ospf_instance_router_id{target=\"clab-telemetry-R14\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "network_instance_protocols_ospf_instance_area_interface_neighbor_adjacency_state{target=\"clab-telemetry-R11\", neighbor_router_id=\"2.2.2.2\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "network_instance_protocols_ospf_instance_area_interface_neighbor_adjacency_state{target=\"clab-telemetry-R11\", neighbor_router_id=\"4.4.4.4\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "network_instance_protocols_ospf_instance_area_interface_neighbor_adjacency_state{target=\"clab-telemetry-R12\", neighbor_router_id=\"1.1.1.1\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "network_instance_protocols_ospf_instance_area_interface_neighbor_adjacency_state{target=\"clab-telemetry-R12\", neighbor_router_id=\"3.3.3.3\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "network_instance_protocols_ospf_instance_area_interface_neighbor_adjacency_state{target=\"clab-telemetry-R12\", neighbor_router_id=\"4.4.4.4\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "network_instance_protocols_ospf_instance_area_interface_neighbor_adjacency_state{target=\"clab-telemetry-R13\", neighbor_router_id=\"2.2.2.2\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "network_instance_protocols_ospf_instance_area_interface_neighbor_adjacency_state{target=\"clab-telemetry-R13\", neighbor_router_id=\"4.4.4.4\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "network_instance_protocols_ospf_instance_area_interface_neighbor_adjacency_state{target=\"clab-telemetry-R14\", neighbor_router_id=\"1.1.1.1\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "network_instance_protocols_ospf_instance_area_interface_neighbor_adjacency_state{target=\"clab-telemetry-R14\", neighbor_router_id=\"2.2.2.2\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "network_instance_protocols_ospf_instance_area_interface_neighbor_adjacency_state{target=\"clab-telemetry-R14\", neighbor_router_id=\"3.3.3.3\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "network_instance_protocols_ospf_instance_backbone_router{target=\"clab-telemetry-R11\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "network_instance_protocols_ospf_instance_backbone_router{target=\"clab-telemetry-R12\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "network_instance_protocols_ospf_instance_backbone_router{target=\"clab-telemetry-R13\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "network_instance_protocols_ospf_instance_backbone_router{target=\"clab-telemetry-R14\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "network_instance_protocols_ospf_instance_as_border_router{target=\"clab-telemetry-R11\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "network_instance_protocols_ospf_instance_as_border_router{target=\"clab-telemetry-R12\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "network_instance_protocols_ospf_instance_as_border_router{target=\"clab-telemetry-R13\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "network_instance_protocols_ospf_instance_as_border_router{target=\"clab-telemetry-R14\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "network_instance_protocols_ospf_instance_area_interface_metric{target=\"clab-telemetry-R11\", interface_interface_name=\"ethernet-1/2.0\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "network_instance_protocols_ospf_instance_area_interface_metric{target=\"clab-telemetry-R11\", interface_interface_name=\"ethernet-1/4.0\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "network_instance_protocols_ospf_instance_area_interface_metric{target=\"clab-telemetry-R11\", interface_interface_name=\"ethernet-1/21.0\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "network_instance_protocols_ospf_instance_area_interface_metric{target=\"clab-telemetry-R12\", interface_interface_name=\"ethernet-1/1.0\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "network_instance_protocols_ospf_instance_area_interface_metric{target=\"clab-telemetry-R12\", interface_interface_name=\"ethernet-1/3.0\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "network_instance_protocols_ospf_instance_area_interface_metric{target=\"clab-telemetry-R12\", interface_interface_name=\"ethernet-1/4.0\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "network_instance_protocols_ospf_instance_area_interface_metric{target=\"clab-telemetry-R12\", interface_interface_name=\"ethernet-1/32.0\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "network_instance_protocols_ospf_instance_area_interface_metric{target=\"clab-telemetry-R13\", interface_interface_name=\"ethernet-1/2.0\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "network_instance_protocols_ospf_instance_area_interface_metric{target=\"clab-telemetry-R13\", interface_interface_name=\"ethernet-1/4.0\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "network_instance_protocols_ospf_instance_area_interface_metric{target=\"clab-telemetry-R14\", interface_interface_name=\"ethernet-1/1.0\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "network_instance_protocols_ospf_instance_area_interface_metric{target=\"clab-telemetry-R14\", interface_interface_name=\"ethernet-1/2.0\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "network_instance_protocols_ospf_instance_area_interface_metric{target=\"clab-telemetry-R14\", interface_interface_name=\"ethernet-1/3.0\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "network_instance_protocols_ospf_instance_area_interface_metric{target=\"clab-telemetry-R14\", interface_interface_name=\"ethernet-1/49.0\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "network_instance_protocols_ospf_instance_area_interface_admin_state{target=\"clab-telemetry-R12\", area_area_id=\"0.0.0.0\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "network_instance_protocols_ospf_instance_area_interface_admin_state{target=\"clab-telemetry-R12\", area_area_id=\"0.0.0.1\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "network_instance_protocols_ospf_instance_admin_state{target=\"clab-telemetry-R21\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "network_instance_protocols_ospf_instance_admin_state{target=\"clab-telemetry-R22\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "network_instance_protocols_ospf_instance_admin_state{target=\"clab-telemetry-R31\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "network_instance_protocols_ospf_instance_admin_state{target=\"clab-telemetry-R32\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "network_instance_protocols_ospf_instance_router_id{target=\"clab-telemetry-R21\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "network_instance_protocols_ospf_instance_router_id{target=\"clab-telemetry-R22\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "network_instance_protocols_ospf_instance_router_id{target=\"clab-telemetry-R31\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "network_instance_protocols_ospf_instance_router_id{target=\"clab-telemetry-R32\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "network_instance_protocols_ospf_instance_area_interface_neighbor_adjacency_state{target=\"clab-telemetry-R21\", neighbor_router_id=\"22.22.22.22\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "network_instance_protocols_ospf_instance_area_interface_neighbor_adjacency_state{target=\"clab-telemetry-R22\", neighbor_router_id=\"21.21.21.21\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "network_instance_protocols_ospf_instance_area_interface_neighbor_adjacency_state{target=\"clab-telemetry-R31\", neighbor_router_id=\"32.32.32.32\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "network_instance_protocols_ospf_instance_area_interface_neighbor_adjacency_state{target=\"clab-telemetry-R32\", neighbor_router_id=\"31.31.31.31\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "network_instance_protocols_ospf_instance_backbone_router{target=\"clab-telemetry-R21\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "network_instance_protocols_ospf_instance_backbone_router{target=\"clab-telemetry-R22\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "network_instance_protocols_ospf_instance_backbone_router{target=\"clab-telemetry-R31\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "network_instance_protocols_ospf_instance_backbone_router{target=\"clab-telemetry-R32\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "network_instance_protocols_ospf_instance_as_border_router{target=\"clab-telemetry-R21\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "network_instance_protocols_ospf_instance_as_border_router{target=\"clab-telemetry-R22\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "network_instance_protocols_ospf_instance_as_border_router{target=\"clab-telemetry-R31\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "network_instance_protocols_ospf_instance_as_border_router{target=\"clab-telemetry-R32\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "network_instance_protocols_ospf_instance_area_interface_metric{target=\"clab-telemetry-R22\", interface_interface_name=\"ethernet-1/1.0\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "network_instance_protocols_ospf_instance_area_interface_metric{target=\"clab-telemetry-R21\", interface_interface_name=\"ethernet-1/2.0\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "network_instance_protocols_ospf_instance_area_interface_metric{target=\"clab-telemetry-R32\", interface_interface_name=\"ethernet-1/1.0\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "network_instance_protocols_ospf_instance_area_interface_metric{target=\"clab-telemetry-R31\", interface_interface_name=\"ethernet-1/2.0\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "network_instance_protocols_ospf_instance_area_interface_metric{target=\"clab-telemetry-R22\", interface_interface_name=\"ethernet-1/49.0\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "network_instance_protocols_ospf_instance_area_interface_metric{target=\"clab-telemetry-R22\", interface_interface_name=\"ethernet-1/49.0\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "network_instance_protocols_ospf_instance_area_interface_admin_state{target=\"clab-telemetry-R21\", area_area_id=\"0.0.0.0\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "network_instance_protocols_ospf_instance_area_interface_admin_state{target=\"clab-telemetry-R31\", area_area_id=\"0.0.0.0\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Neighbor Uptimes AS1",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 11, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "network_instance_protocols_ospf_instance_area_interface_neighbor_up_time{subscription_name=\"sub-ospf\"}",
     "legendFormat": "{{target}} -> {{neighbor_router_id}}"
    }
   ]
  },
  {
   "title": "Neighbor Uptimes AS2",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 5, "x": 12, "y": 11 },
   "targets": [
    {
     "expr": "network_instance_protocols_ospf_instance_area_interface_neighbor_up_time{subscription_name=\"sub-ospf\"}",
     "legendFormat": "{{target}} -> {{neighbor_router_id}}"
    }
   ]
  },
  {
   "title": "Neighbor Uptimes AS3",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 17, "y": 11 },
   "targets": [
    {
     "expr": "network_instance_protocols_ospf_instance_area_interface_neighbor_up_time{subscription_name=\"sub-ospf\"}",
     "legendFormat": "{{target}} -> {{neighbor_router_id}}"
    }
   ]
  },
  {
   "title": "Active OSPF interfaces",
   "type": "stat",
   "gridPos": { "h": 4, "w": 11, "x": 12, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(target) (network_instance_protocols_ospf_instance_area_active_interfaces{subscription_name=\"sub-ospf\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active OSPF routers",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 2, "x": 0, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(network_instance_protocols_ospf_instance_admin_state{admin_state=\"enable\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "OSPF border routers",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 5, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(network_instance_protocols_ospf_instance_as_border_router{subscription_name=\"sub-ospf\", as_border_router=\"true\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "OSPF backbone routers",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 10, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(network_instance_protocols_ospf_instance_backbone_router{backbone_router=\"true\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "OSPF neighbours",
   "type": "stat",
   "gridPos": { "h": 4, "w": 11, "x": 12, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(target) (network_instance_protocols_ospf_instance_area_interface_neighbor_count{subscription_name=\"sub-ospf\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}