{
 "title": "Routes",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "total routes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(target) (network_instance_route_table_ipv4_unicast_statistics_active_routes{subscription_name=\"sub-interface\", network_instance_name!=\"mgmt\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "R11",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Active Routes",
     "type": "table",
     "gridPos": { "h": 19, "w": 13, "x": 0, "y": 5 },
     "targets": [
      {
       "expr": "network_instance_route_table_ipv4_unicast_route_metric{subscription_name=\"sub-interface\", target=\"clab-telemetry-R11\", network_instance_name!=\"mgmt\"}",
       "legendFormat": "{{metric}}"
      },
      {
       "expr": "network_instance_route_table_ipv4_unicast_route_next_hop_group{subscription_name=\"sub-interface\", target=\"clab-telemetry-R11\", network_instance_name!=\"mgmt\"}",
       "legendFormat": "{{metric}}"
      },
      {
       "expr": "network_instance_route_table_ipv4_unicast_route_preference{subscription_name=\"sub-interface\", target=\"clab-telemetry-R11\", network_instance_name!=\"mgmt\"}",
       "legendFormat": "{{metric}}"
      },
      {
       "expr": "network_instance_route_table_next_hop_type{subscription_name=\"sub-interface\", target=\"clab-telemetry-R11\", network_instance_name!=\"mgmt\"}",
       "legendFormat": "{{metric}}"
      }
     ]
    },
    {
     "title": "next hop mapping",
     "type": "table",
     "gridPos": { "h": 11, "w": 4, "x": 13, "y": 5 },
     "targets": [
      {
       "expr": "network_instance_route_table_next_hop_group_next_hop_next_hop{subscription_name=\"sub-interface\", target=\"clab-telemetry-R11\", network_instance_name!=\"mgmt\"}",
       "legendFormat": "{{metric}}"
      },
      {
       "expr": "network_instance_route_table_next_hop_subinterface{subscription_name=\"sub-interface\", target=\"clab-telemetry-R11\", network_instance_name!=\"mgmt\"}",
       "legendFormat": "{{metric}}"
      }
     ]
    },
    {
     "title": "next hop deails",
     "type": "table",
     "gridPos": { "h": 11, "w": 7, "x": 17, "y": 5 },
     "targets": [
      {
       "expr": "network_instance_route_table_next_hop_type{subscription_name=\"sub-interface\", target=\"clab-telemetry-R11\", network_instance_name!=\"mgmt\"}",
       "legendFormat": "{{metric}}"
      },
      {
       "expr": "network_instance_route_table_next_hop_subinterface{subscription_name=\"sub-interface\", target=\"clab-telemetry-R11\", network_instance_name!=\"mgmt\"}",
       "legendFormat": "{{metric}}"
      },
      {
       "expr": "network_instance_route_table_next_hop_ip_address{subscription_name=\"sub-interface\", target=\"clab-telemetry-R11\", network_instance_name!=\"mgmt\"}",
       "legendFormat": "{{metric}}"
      }
     ]
    }
   ]
  },
  {
   "title": "R12",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Active Routes",
     "type": "table",
     "gridPos": { "h": 21, "w": 13, "x": 0, "y": 6 },
     "targets": [
      {
       "expr": "network_instance_route_table_ipv4_unicast_route_metric{subscription_name=\"sub-interface\", target=\"clab-telemetry-R12\", network_instance_name!=\"mgmt\"}",
       "legendFormat": "{{metric}}"
      },
      {
       "expr": "network_instance_route_table_ipv4_unicast_route_next_hop_group{subscription_name=\"sub-interface\", target=\"clab-telemetry-R12\", network_instance_name!=\"mgmt\"}",
       "legendFormat": "{{metric}}"
      },
      {
       "expr": "network_instance_route_table_ipv4_unicast_route_preference{subscription_name=\"sub-interface\", target=\"clab-telemetry-R12\", network_instance_name!=\"mgmt\"}",
       "legendFormat": "{{metric}}"
      },
      {
       "expr": "network_instance_route_table_next_hop_type{subscription_name=\"sub-interface\", target=\"clab-telemetry-R12\", network_instance_name!=\"mgmt\"}",
       "legendFormat": "{{metric}}"
      }
     ]
    },
    {
     "title": "next hop mapping",
     "type": "table",
     "gridPos": { "h": 14, "w": 4, "x": 13, "y": 6 },
     "targets": [
      {
       "expr": "network_instance_route_table_next_hop_group_next_hop_next_hop{subscription_name=\"sub-interface\", target=\"clab-telemetry-R12\", network_instance_name!=\"mgmt\"}",
       "legendFormat": "{{metric}}"
      },
      {
       "expr": "network_instance_route_table_next_hop_subinterface{subscription_name=\"sub-interface\", target=\"clab-telemetry-R12\", network_instance_name!=\"mgmt\"}",
       "legendFormat": "{{metric}}"
      }
     ]
    },
    {
     "title": "next hop deails",
     "type": "table",
     "gridPos": { "h": 14, "w": 7, "x": 17, "y": 6 },
     "targets": [
      {
       "expr": "network_instance_route_table_next_hop_type{subscription_name=\"sub-interface\", target=\"clab-telemetry-R12\", network_instance_name!=\"mgmt\"}",
       "legendFormat": "{{metric}}"
      },
      {
       "expr": "network_instance_route_table_next_hop_subinterface{subscription_name=\"sub-interface\", target=\"clab-telemetry-R12\", network_instance_name!=\"mgmt\"}",
       "legendFormat": "{{metric}}"
      },
      {
       "expr": "network_instance_route_table_next_hop_ip_address{subscription_name=\"sub-interface\", target=\"clab-telemetry-R12\", network_instance_name!=\"mgmt\"}",
       "legendFormat": "{{metric}}"
      }
     ]
    }
   ]
  },
  {
   "title": "R13",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Active Routes",
     "type": "table",
     "gridPos": { "h": 18, "w": 13, "x": 0, "y": 7 },
     "targets": [
      {
       "expr": "network_instance_route_table_ipv4_unicast_route_metric{subscription_name=\"sub-interface\", target=\"clab-telemetry-R13\", network_instance_name!=\"mgmt\"}",
       "legendFormat": "{{metric}}"
      },
      {
       "expr": "network_instance_route_table_ipv4_unicast_route_next_hop_group{subscription_name=\"sub-interface\", target=\"clab-telemetry-R13\", network_instance_name!=\"mgmt\"}",
       "legendFormat": "{{metric}}"
      },
      {
       "expr": "network_instance_route_table_ipv4_unicast_route_preference{subscription_name=\"sub-interface\", target=\"clab-telemetry-R13\", network_instance_name!=\"mgmt\"}",
       "legendFormat": "{{metric}}"
      },
      {
       "expr": "network_instance_route_table_next_hop_type{subscription_name=\"sub-interface\", target=\"clab-telemetry-R13\", network_instance_name!=\"mgmt\"}",
       "legendFormat": "{{metric}}"
      }
     ]
    },
    {
     "title": "next hop mapping",
     "type": "table",
     "gridPos": { "h": 11, "w": 4, "x": 13, "y": 7 },
     "targets": [
      {
       "expr": "network_instance_route_table_next_hop_group_next_hop_next_hop{subscription_name=\"sub-interface\", target=\"clab-telemetry-R13\", network_instance_name!=\"mgmt\"}",
       "legendFormat": "{{metric}}"
      },
      {
       "expr": "network_instance_route_table_next_hop_subinterface{subscription_name=\"sub-interface\", target=\"clab-telemetry-R13\", network_instance_name!=\"mgmt\"}",
       "legendFormat": "{{metric}}"
      }
     ]
    },
    {
     "title": "next hop deails",
     "type": "table",
     "gridPos": { "h": 11, "w": 7, "x": 17, "y": 7 },
     "targets": [
      {
       "expr": "network_instance_route_table_next_hop_type{subscription_name=\"sub-interface\", target=\"clab-telemetry-R13\", network_instance_name!=\"mgmt\"}",
       "legendFormat": "{{metric}}"
      },
      {
       "expr": "network_instance_route_table_next_hop_subinterface{subscription_name=\"sub-interface\", target=\"clab-telemetry-R13\", network_instance_name!=\"mgmt\"}",
       "legendFormat": "{{metric}}"
      },
      {
       "expr": "network_instance_route_table_next_hop_ip_address{subscription_name=\"sub-interface\", target=\"clab-telemetry-R13\", network_instance_name!=\"mgmt\"}",
       "legendFormat": "{{metric}}"
      }
     ]
    }
   ]
  },
  {
   "title": "R14",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Active Routes",
     "type": "table",
     "gridPos": { "h": 22, "w": 13, "x": 0, "y": 8 },
     "targets": [
      {
       "expr": "network_instance_route_table_ipv4_unicast_route_metric{subscription_name=\"sub-interface\", target=\"clab-telemetry-R14\", network_instance_name!=\"mgmt\"}",
       "legendFormat": "{{metric}}"
      },
      {
       "expr": "network_instance_route_table_ipv4_unicast_route_next_hop_group{subscription_name=\"sub-interface\", target=\"clab-telemetry-R14\", network_instance_name!=\"mgmt\"}",
       "legendFormat": "{{metric}}"
      },
      {
       "expr": "network_instance_route_table_ipv4_unicast_route_preference{subscription_name=\"sub-interface\", target=\"clab-telemetry-R14\", network_instance_name!=\"mgmt\"}",
       "legendFormat": "{{metric}}"
      },
      {
       "expr": "network_instance_route_table_next_hop_type{subscription_name=\"sub-interface\", target=\"clab-telemetry-R14\", network_instance_name!=\"mgmt\"}",
       "legendFormat": "{{metric}}"
      }
     ]
    },
    {
     "title": "next hop mapping",
     "type": "table",
     "gridPos": { "h": 11, "w": 4, "x": 13, "y": 8 },
     "targets": [
      {
       "expr": "network_instance_route_table_next_hop_group_next_hop_next_hop{subscription_name=\"sub-interface\", target=\"clab-telemetry-R14\", network_instance_name!=\"mgmt\"}",
       "legendFormat": "{{metric}}"
      },
      {
       "expr": "network_instance_route_table_next_hop_subinterface{subscription_name=\"sub-interface\", target=\"clab-telemetry-R14\", network_instance_name!=\"mgmt\"}",
       "legendFormat": "{{metric}}"
      }
     ]
    },
    {
     "title": "next hop deails",
     "type": "table",
     "gridPos": { "h": 11, "w": 7, "x": 17, "y": 8 },
     "targets": [
      {
       "expr": "network_instance_route_table_next_hop_type{subscription_name=\"sub-interface\", target=\"clab-telemetry-R14\", network_instance_name!=\"mgmt\"}",
       "legendFormat": "{{metric}}"
      },
      {
       "expr": "network_instance_route_table_next_hop_subinterface{subscription_name=\"sub-interface\", target=\"clab-telemetry-R14\", network_instance_name!=\"mgmt\"}",
       "legendFormat": "{{metric}}"
      },
      {
       "expr": "network_instance_route_table_next_hop_ip_address{subscription_name=\"sub-interface\", target=\"clab-telemetry-R14\", network_instance_name!=\"mgmt\"}",
       "legendFormat": "{{metric}}"
      }
     ]
    }
   ]
  },
  {
   "title": "R21",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Active Routes",
     "type": "table",
     "gridPos": { "h": 19, "w": 13, "x": 0, "y": 9 },
     "targets": [
      {
       "expr": "network_instance_route_table_ipv4_unicast_route_metric{subscription_name=\"sub-interface\", target=\"clab-telemetry-R21\", network_instance_name!=\"mgmt\"}",
       "legendFormat": "{{metric}}"
      },
      {
       "expr": "network_instance_route_table_ipv4_unicast_route_next_hop_group{subscription_name=\"sub-interface\", target=\"clab-telemetry-R21\", network_instance_name!=\"mgmt\"}",
       "legendFormat": "{{metric}}"
      },
      {
       "expr": "network_instance_route_table_ipv4_unicast_route_preference{subscription_name=\"sub-interface\", target=\"clab-telemetry-R21\", network_instance_name!=\"mgmt\"}",
       "legendFormat": "{{metric}}"
      },
      {
       "expr": "network_instance_route_table_next_hop_type{subscription_name=\"sub-interface\", target=\"clab-telemetry-R21\", network_instance_name!=\"mgmt\"}",
       "legendFormat": "{{metric}}"
      }
     ]
    },
    {
     "title": "next hop mapping",
     "type": "table",
     "gridPos": { "h": 11, "w": 4, "x": 13, "y": 9 },
     "targets": [
      {
       "expr": "network_instance_route_table_next_hop_group_next_hop_next_hop{subscription_name=\"sub-interface\", target=\"clab-telemetry-R21\", network_instance_name!=\"mgmt\"}",
       "legendFormat": "{{metric}}"
      },
      {
       "expr": "network_instance_route_table_next_hop_subinterface{subscription_name=\"sub-interface\", target=\"clab-telemetry-R21\", network_instance_name!=\"mgmt\"}",
       "legendFormat": "{{metric}}"
      }
     ]
    },
    {
     "title": "next hop deails",
     "type": "table",
     "gridPos": { "h": 11, "w": 7, "x": 17, "y": 9 },
     "targets": [
      {
       "expr": "network_instance_route_table_next_hop_type{subscription_name=\"sub-interface\", target=\"clab-telemetry-R21\", network_instance_name!=\"mgmt\"}",
       "legendFormat": "{{metric}}"
      },
      {
       "expr": "network_instance_route_table_next_hop_subinterface{subscription_name=\"sub-interface\", target=\"clab-telemetry-R21\", network_instance_name!=\"mgmt\"}",
       "legendFormat": "{{metric}}"
      },
      {
       "expr": "network_instance_route_table_next_hop_ip_address{subscription_name=\"sub-interface\", target=\"clab-telemetry-R21\", network_instance_name!=\"mgmt\"}",
       "legendFormat": "{{metric}}"
      }
     ]
    }
   ]
  },
  {
   "title": "R22",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Active Routes",
     "type": "table",
     "gridPos": { "h": 19, "w": 13, "x": 0, "y": 10 },
     "targets": [
      {
       "expr": "network_instance_route_table_ipv4_unicast_route_metric{subscription_name=\"sub-interface\", target=\"clab-telemetry-R22\", network_instance_name!=\"mgmt\"}",
       "legendFormat": "{{metric}}"
      },
      {
       "expr": "network_instance_route_table_ipv4_unicast_route_next_hop_group{subscription_name=\"sub-interface\", target=\"clab-telemetry-R22\", network_instance_name!=\"mgmt\"}",
       "legendFormat": "{{metric}}"
      },
      {
       "expr": "network_instance_route_table_ipv4_unicast_route_preference{subscription_name=\"sub-interface\", target=\"clab-telemetry-R22\", network_instance_name!=\"mgmt\"}",
       "legendFormat": "{{metric}}"
      },
      {
       "expr": "network_instance_route_table_next_hop_type{subscription_name=\"sub-interface\", target=\"clab-telemetry-R22\", network_instance_name!=\"mgmt\"}",
       "legendFormat": "{{metric}}"
      }
     ]
    },
    {
     "title": "next hop mapping",
     "type": "table",
     "gridPos": { "h": 11, "w": 4, "x": 13, "y": 10 },
     "targets": [
      {
       "expr": "network_instance_route_table_next_hop_group_next_hop_next_hop{subscription_name=\"sub-interface\", target=\"clab-telemetry-R22\", network_instance_name!=\"mgmt\"}",
       "legendFormat": "{{metric}}"
      },
      {
       "expr": "network_instance_route_table_next_hop_subinterface{subscription_name=\"sub-interface\", target=\"clab-telemetry-R22\", network_instance_name!=\"mgmt\"}",
       "legendFormat": "{{metric}}"
      }
     ]
    },
    {
     "title": "next hop deails",
     "type": "table",
     "gridPos": { "h": 11, "w": 7, "x": 17, "y": 10 },
     "targets": [
      {
       "expr": "network_instance_route_table_next_hop_type{subscription_name=\"sub-interface\", target=\"clab-telemetry-R22\", network_instance_name!=\"mgmt\"}",
       "legendFormat": "{{metric}}"
      },
      {
       "expr": "network_instance_route_table_next_hop_subinterface{subscription_name=\"sub-interface\", target=\"clab-telemetry-R22\", network_instance_name!=\"mgmt\"}",
       "legendFormat": "{{metric}}"
      },
      {
       "expr": "network_instance_route_table_next_hop_ip_address{subscription_name=\"sub-interface\", target=\"clab-telemetry-R22\", network_instance_name!=\"mgmt\"}",
       "legendFormat": "{{metric}}"
      }
     ]
    }
   ]
  },
  {
   "title": "R31",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Active Routes",
     "type": "table",
     "gridPos": { "h": 19, "w": 13, "x": 0, "y": 11 },
     "targets": [
      {
       "expr": "network_instance_route_table_ipv4_unicast_route_metric{subscription_name=\"sub-interface\", target=\"clab-telemetry-R31\", network_instance_name!=\"mgmt\"}",
       "legendFormat": "{{metric}}"
      },
      {
       "expr": "network_instance_route_table_ipv4_unicast_route_next_hop_group{subscription_name=\"sub-interface\", target=\"clab-telemetry-R31\", network_instance_name!=\"mgmt\"}",
       "legendFormat": "{{metric}}"
      },
      {
       "expr": "network_instance_route_table_ipv4_unicast_route_preference{subscription_name=\"sub-interface\", target=\"clab-telemetry-R31\", network_instance_name!=\"mgmt\"}",
       "legendFormat": "{{metric}}"
      },
      {
       "expr": "network_instance_route_table_next_hop_type{subscription_name=\"sub-interface\", target=\"clab-telemetry-R31\", network_instance_name!=\"mgmt\"}",
       "legendFormat": "{{metric}}"
      }
     ]
    },
    {
     "title": "next hop mapping",
     "type": "table",
     "gridPos": { "h": 11, "w": 4, "x": 13, "y": 11 },
     "targets": [
      {
       "expr": "network_instance_route_table_next_hop_group_next_hop_next_hop{subscription_name=\"sub-interface\", target=\"clab-telemetry-R31\", network_instance_name!=\"mgmt\"}",
       "legendFormat": "{{metric}}"
      },
      {
       "expr": "network_instance_route_table_next_hop_subinterface{subscription_name=\"sub-interface\", target=\"clab-telemetry-R31\", network_instance_name!=\"mgmt\"}",
       "legendFormat": "{{metric}}"
      }
     ]
    },
    {
     "title": "next hop deails",
     "type": "table",
     "gridPos": { "h": 11, "w": 7, "x": 17, "y": 11 },
     "targets": [
      {
       "expr": "network_instance_route_table_next_hop_type{subscription_name=\"sub-interface\", target=\"clab-telemetry-R31\", network_instance_name!=\"mgmt\"}",
       "legendFormat": "{{metric}}"
      },
      {
       "expr": "network_instance_route_table_next_hop_subinterface{subscription_name=\"sub-interface\", target=\"clab-telemetry-R31\", network_instance_name!=\"mgmt\"}",
       "legendFormat": "{{metric}}"
      },
      {
       "expr": "network_instance_route_table_next_hop_ip_address{subscription_name=\"sub-interface\", target=\"clab-telemetry-R31\", network_instance_name!=\"mgmt\"}",
       "legendFormat": "{{metric}}"
      }
     ]
    }
   ]
  },
  {
   "title": "R32",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Active Routes",
     "type": "table",
     "gridPos": { "h": 19, "w": 13, "x": 0, "y": 12 },
     "targets": [
      {
       "expr": "network_instance_route_table_ipv4_unicast_route_metric{subscription_name=\"sub-interface\", target=\"clab-telemetry-R32\", network_instance_name!=\"mgmt\"}",
       "legendFormat": "{{metric}}"
      },
      {
       "expr": "network_instance_route_table_ipv4_unicast_route_next_hop_group{subscription_name=\"sub-interface\", target=\"clab-telemetry-R32\", network_instance_name!=\"mgmt\"}",
       "legendFormat": "{{metric}}"
      },
      {
       "expr": "network_instance_route_table_ipv4_unicast_route_preference{subscription_name=\"sub-interface\", target=\"clab-telemetry-R32\", network_instance_name!=\"mgmt\"}",
       "legendFormat": "{{metric}}"
      },
      {
       "expr": "network_instance_route_table_next_hop_type{subscription_name=\"sub-interface\", target=\"clab-telemetry-R32\", network_instance_name!=\"mgmt\"}",
       "legendFormat": "{{metric}}"
      }
     ]
    },
    {
     "title": "next hop mapping",
     "type": "table",
     "gridPos": { "h": 11, "w": 4, "x": 13, "y": 12 },
     "targets": [
      {
       "expr": "network_instance_route_table_next_hop_group_next_hop_next_hop{subscription_name=\"sub-interface\", target=\"clab-telemetry-R32\", network_instance_name!=\"mgmt\"}",
       "legendFormat": "{{metric}}"
      },
      {
       "expr": "network_instance_route_table_next_hop_subinterface{subscription_name=\"sub-interface\", target=\"clab-telemetry-R32\", network_instance_name!=\"mgmt\"}",
       "legendFormat": "{{metric}}"
      }
     ]
    },
    {
     "title": "next hop deails",
     "type": "table",
     "gridPos": { "h": 11, "w": 7, "x": 17, "y": 12 },
     "targets": [
      {
       "expr": "network_instance_route_table_next_hop_type{subscription_name=\"sub-interface\", target=\"clab-telemetry-R32\", network_instance_name!=\"mgmt\"}",
       "legendFormat": "{{metric}}"
      },
      {
       "expr": "network_instance_route_table_next_hop_subinterface{subscription_name=\"sub-interface\", target=\"clab-telemetry-R32\", network_instance_name!=\"mgmt\"}",
       "legendFormat": "{{metric}}"
      },
      {
       "expr": "network_instance_route_table_next_hop_ip_address{subscription_name=\"sub-interface\", target=\"clab-telemetry-R32\", network_instance_name!=\"mgmt\"}",
       "legendFormat": "{{metric}}"
      }
     ]
    }
   ]
  }
 ]
}