{
 "title": "system",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "in packets",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 11, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "avg by(target) (sum by(target) (rate(interface_subinterface_statistics_in_packets{interface_name!=\"mgmt0\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "out packets",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 11, "x": 11, "y": 0 },
   "targets": [
    {
     "expr": "avg by(target) (sum by(target) (rate(interface_subinterface_statistics_out_packets{interface_name!=\"mgmt0\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 11, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "platform_control_memory_free{subscription_name=\"sub-system\"}",
     "legendFormat": "{{target}}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "gauge",
   "gridPos": { "h": 12, "w": 11, "x": 11, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "platform_control_cpu_total_instant{subscription_name=\"sub-system\"}",
     "legendFormat": "{{target}}"
    }
   ]
  },
  {
   "title": "out octets per router",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 11, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg by(target) (sum by(target) (rate(interface_subinterface_statistics_out_octets{interface_name=\"mgmt0\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "out octets all",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 11, "x": 11, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(avg by(target) (sum by(target) (rate(interface_subinterface_statistics_out_octets{interface_name=\"mgmt0\"}[$__rate_interval]))))",
     "legendFormat": "throughput"
    }
   ]
  }
 ]
}