{
 "title": "OSPF test",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "BGP Last established",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "network_instance_protocols_bgp_neighbor_last_established{subscription_name=\"sub-bgp\", target=\"clab-telemetry-R12\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": " BGP last event",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "network_instance_protocols_bgp_neighbor_last_event{subscription_name=\"sub-bgp\", target=\"clab-telemetry-R12\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "OSPF neighbours",
   "type": "stat",
   "gridPos": { "h": 3, "w": 11, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(target) (network_instance_protocols_ospf_instance_area_interface_neighbor_count{subscription_name=\"sub-ospf\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "BGP Last established ",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "network_instance_protocols_bgp_neighbor_last_established{subscription_name=\"sub-bgp\", target=\"clab-telemetry-R11\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": " BGP last event",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "network_instance_protocols_bgp_neighbor_last_event{subscription_name=\"sub-bgp\", target=\"clab-telemetry-R11\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active OSPF interfaces",
   "type": "stat",
   "gridPos": { "h": 3, "w": 11, "x": 6, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(target) (network_instance_protocols_ospf_instance_area_active_interfaces{subscription_name=\"sub-ospf\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "OSPF graph",
   "type": "agenty-flowcharting-panel",
   "gridPos": { "h": 19, "w": 11, "x": 6, "y": 6 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "network_instance_protocols_ospf_instance_admin_state{target=\"clab-telemetry-R11\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "network_instance_protocols_ospf_instance_admin_state{target=\"clab-telemetry-R12\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "network_instance_protocols_ospf_instance_admin_state{target=\"clab-telemetry-R13\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "network_instance_protocols_ospf_instance_admin_state{target=\"clab-telemetry-R14\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "network_instance_protocols_ospf_instance_router_id{target=\"clab-telemetry-R11\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "network_instance_protocols_ospf_instance_router_id{target=\"clab-telemetry-R12\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "network_instance_protocols_ospf_instance_router_id{target=\"clab-telemetry-R13\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "network_instance_protocols_ospf_instance_router_id{target=\"clab-telemetry-R14\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "network_instance_protocols_ospf_instance_area_interface_neighbor_adjacency_state{target=\"clab-telemetry-R11\", neighbor_router_id=\"2.2.2.2\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "network_instance_protocols_ospf_instance_area_interface_neighbor_adjacency_state{target=\"clab-telemetry-R11\", neighbor_router_id=\"4.4.4.4\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "network_instance_protocols_ospf_instance_area_interface_neighbor_adjacency_state{target=\"clab-telemetry-R12\", neighbor_router_id=\"1.1.1.1\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "network_instance_protocols_ospf_instance_area_interface_neighbor_adjacency_state{target=\"clab-telemetry-R12\", neighbor_router_id=\"3.3.3.3\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "network_instance_protocols_ospf_instance_area_interface_neighbor_adjacency_state{target=\"clab-telemetry-R12\", neighbor_router_id=\"4.4.4.4\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "network_instance_protocols_ospf_instance_area_interface_neighbor_adjacency_state{target=\"clab-telemetry-R13\", neighbor_router_id=\"2.2.2.2\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "network_instance_protocols_ospf_instance_area_interface_neighbor_adjacency_state{target=\"clab-telemetry-R13\", neighbor_router_id=\"4.4.4.4\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "network_instance_protocols_ospf_instance_area_interface_neighbor_adjacency_state{target=\"clab-telemetry-R14\", neighbor_router_id=\"1.1.1.1\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "network_instance_protocols_ospf_instance_area_interface_neighbor_adjacency_state{target=\"clab-telemetry-R14\", neighbor_router_id=\"2.2.2.2\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "network_instance_protocols_ospf_instance_area_interface_neighbor_adjacency_state{target=\"clab-telemetry-R14\", neighbor_router_id=\"3.3.3.3\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "network_instance_protocols_ospf_instance_backbone_router{target=\"clab-telemetry-R11\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "network_instance_protocols_ospf_instance_backbone_router{target=\"clab-telemetry-R12\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "network_instance_protocols_ospf_instance_backbone_router{target=\"clab-telemetry-R13\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "network_instance_protocols_ospf_instance_backbone_router{target=\"clab-telemetry-R14\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "network_instance_protocols_ospf_instance_as_border_router{target=\"clab-telemetry-R11\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "network_instance_protocols_ospf_instance_as_border_router{target=\"clab-telemetry-R12\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "network_instance_protocols_ospf_instance_as_border_router{target=\"clab-telemetry-R13\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "network_instance_protocols_ospf_instance_as_border_router{target=\"clab-telemetry-R14\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "network_instance_protocols_ospf_instance_area_interface_metric{target=\"clab-telemetry-R11\", interface_interface_name=\"ethernet-1/2.0\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "network_instance_protocols_ospf_instance_area_interface_metric{target=\"clab-telemetry-R11\", interface_interface_name=\"ethernet-1/4.0\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "network_instance_protocols_ospf_instance_area_interface_metric{target=\"clab-telemetry-R11\", interface_interface_name=\"ethernet-1/21.0\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "network_instance_protocols_ospf_instance_area_interface_metric{target=\"clab-telemetry-R12\", interface_interface_name=\"ethernet-1/1.0\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "network_instance_protocols_ospf_instance_area_interface_metric{target=\"clab-telemetry-R12\", interface_interface_name=\"ethernet-1/3.0\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "network_instance_protocols_ospf_instance_area_interface_metric{target=\"clab-telemetry-R12\", interface_interface_name=\"ethernet-1/4.0\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "network_instance_protocols_ospf_instance_area_interface_metric{target=\"clab-telemetry-R12\", interface_interface_name=\"ethernet-1/32.0\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "network_instance_protocols_ospf_instance_area_interface_metric{target=\"clab-telemetry-R13\", interface_interface_name=\"ethernet-1/2.0\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "network_instance_protocols_ospf_instance_area_interface_metric{target=\"clab-telemetry-R13\", interface_interface_name=\"ethernet-1/4.0\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "network_instance_protocols_ospf_instance_area_interface_metric{target=\"clab-telemetry-R14\", interface_interface_name=\"ethernet-1/1.0\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "network_instance_protocols_ospf_instance_area_interface_metric{target=\"clab-telemetry-R14\", interface_interface_name=\"ethernet-1/2.0\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "network_instance_protocols_ospf_instance_area_interface_metric{target=\"clab-telemetry-R14\", interface_interface_name=\"ethernet-1/3.0\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "network_instance_protocols_ospf_instance_area_interface_metric{target=\"clab-telemetry-R14\", interface_interface_name=\"ethernet-1/49.0\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "network_instance_protocols_ospf_instance_area_interface_admin_state{target=\"clab-telemetry-R12\", area_area_id=\"0.0.0.0\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "network_instance_protocols_ospf_instance_area_interface_admin_state{target=\"clab-telemetry-R12\", area_area_id=\"0.0.0.1\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "network_instance_protocols_bgp_neighbor_admin_state{subscription_name=\"sub-bgp\", target=\"clab-telemetry-R11\", neighbor_peer_address=\"12.12.12.2\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "network_instance_protocols_bgp_neighbor_admin_state{subscription_name=\"sub-bgp\", target=\"clab-telemetry-R12\", neighbor_peer_address=\"13.13.13.2\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "network_instance_protocols_bgp_neighbor_peer_as{subscription_name=\"sub-bgp\", target=\"clab-telemetry-R12\", neighbor_peer_address=\"13.13.13.2\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "network_instance_protocols_bgp_neighbor_peer_as{subscription_name=\"sub-bgp\", target=\"clab-telemetry-R11\", neighbor_peer_address=\"12.12.12.2\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "network_instance_protocols_bgp_autonomous_system{subscription_name=\"sub-bgp\", target=\"clab-telemetry-R11\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "network_instance_protocols_bgp_neighbor_peer_group{subscription_name=\"sub-bgp\", target=\"clab-telemetry-R11\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "network_instance_protocols_bgp_neighbor_peer_group{subscription_name=\"sub-bgp\", target=\"clab-telemetry-R12\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "network_instance_protocols_bgp_neighbor_sent_messages_total_messages{subscription_name=\"sub-bgp\", target=\"clab-telemetry-R12\"}",
     "legendFormat": "{{}}"
    },
    {
     "expr": "network_instance_protocols_bgp_neighbor_received_messages_total_messages{subscription_name=\"sub-bgp\", target=\"clab-telemetry-R12\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 17, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "network_instance_protocols_bgp_neighbor_sent_messages_total_messages{subscription_name=\"sub-bgp\", target=\"clab-telemetry-R11\"}",
     "legendFormat": "{{}}"
    },
    {
     "expr": "network_instance_protocols_bgp_neighbor_received_messages_total_messages{subscription_name=\"sub-bgp\", target=\"clab-telemetry-R11\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 17, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "network_instance_protocols_bgp_neighbor_export_policy{subscription_name=\"sub-bgp\", target=\"clab-telemetry-R11\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "network_instance_protocols_bgp_neighbor_import_policy{subscription_name=\"sub-bgp\", target=\"clab-telemetry-R11\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 20, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "network_instance_protocols_bgp_neighbor_export_policy{subscription_name=\"sub-bgp\", target=\"clab-telemetry-R12\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "network_instance_protocols_bgp_neighbor_import_policy{subscription_name=\"sub-bgp\", target=\"clab-telemetry-R12\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "network_instance_protocols_bgp_neighbor_export_policy{subscription_name=\"sub-bgp\", target=\"clab-telemetry-R11\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "network_instance_protocols_bgp_neighbor_import_policy{subscription_name=\"sub-bgp\", target=\"clab-telemetry-R11\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "network_instance_protocols_bgp_neighbor_export_policy{subscription_name=\"sub-bgp\", target=\"clab-telemetry-R12\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "network_instance_protocols_bgp_neighbor_import_policy{subscription_name=\"sub-bgp\", target=\"clab-telemetry-R12\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 17, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "network_instance_protocols_bgp_neighbor_ipv4_unicast_received_routes{subscription_name=\"sub-bgp\", target=\"clab-telemetry-R11\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "network_instance_protocols_bgp_neighbor_ipv4_unicast_sent_routes{subscription_name=\"sub-bgp\", target=\"clab-telemetry-R11\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "network_instance_protocols_bgp_neighbor_ipv4_unicast_received_routes{subscription_name=\"sub-bgp\", target=\"clab-telemetry-R12\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "network_instance_protocols_bgp_neighbor_ipv4_unicast_sent_routes{subscription_name=\"sub-bgp\", target=\"clab-telemetry-R12\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active OSPF routers",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 2, "x": 0, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(network_instance_protocols_ospf_instance_admin_state)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "OSPF border routers",
   "type": "stat",
   "gridPos": { "h": 8, "w": 2, "x": 2, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(network_instance_protocols_ospf_instance_as_border_router{subscription_name=\"sub-ospf\", as_border_router=\"true\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "OSPF backbone routers",
   "type": "stat",
   "gridPos": { "h": 8, "w": 2, "x": 4, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(network_instance_protocols_ospf_instance_backbone_router{backbone_router=\"true\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Neighbor Uptimes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 17, "x": 6, "y": 25 },
   "targets": [
    {
     "expr": "network_instance_protocols_ospf_instance_area_interface_neighbor_up_time{subscription_name=\"sub-ospf\"}",
     "legendFormat": "{{target}} -> {{neighbor_router_id}}"
    }
   ]
  }
 ]
}