{
 "title": "BGP",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Enabled BGP Routers",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 2, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(network_instance_protocols_bgp_admin_state{admin_state=\"enable\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total BGP Active Routes",
   "type": "stat",
   "gridPos": { "h": 6, "w": 15, "x": 2, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "network_instance_protocols_bgp_statistics_total_active_routes",
     "legendFormat": "{{target}}"
    }
   ]
  },
  {
   "title": "BGP graph",
   "type": "agenty-flowcharting-panel",
   "gridPos": { "h": 20, "w": 17, "x": 0, "y": 6 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "network_instance_protocols_bgp_router_id{target=\"clab-telemetry-R11\"}",
     "legendFormat": "{{router_id}}"
    },
    {
     "expr": "network_instance_protocols_bgp_router_id{target=\"clab-telemetry-R12\"}",
     "legendFormat": "{{router_id}}"
    },
    {
     "expr": "network_instance_protocols_bgp_router_id{target=\"clab-telemetry-R21\"}",
     "legendFormat": "{{router_id}}"
    },
    {
     "expr": "network_instance_protocols_bgp_router_id{target=\"clab-telemetry-R22\"}",
     "legendFormat": "{{router_id}}"
    },
    {
     "expr": "network_instance_protocols_bgp_router_id{target=\"clab-telemetry-R31\"}",
     "legendFormat": "{{router_id}}"
    },
    {
     "expr": "network_instance_protocols_bgp_router_id{target=\"clab-telemetry-R32\"}",
     "legendFormat": "{{router_id}}"
    },
    {
     "expr": "network_instance_protocols_bgp_autonomous_system{target=\"clab-telemetry-R11\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "network_instance_protocols_bgp_autonomous_system{target=\"clab-telemetry-R22\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "network_instance_protocols_bgp_autonomous_system{target=\"clab-telemetry-R31\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "network_instance_protocols_bgp_admin_state{target=\"clab-telemetry-R11\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "network_instance_protocols_bgp_admin_state{target=\"clab-telemetry-R12\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "network_instance_protocols_bgp_admin_state{target=\"clab-telemetry-R21\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "network_instance_protocols_bgp_admin_state{target=\"clab-telemetry-R22\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "network_instance_protocols_bgp_admin_state{target=\"clab-telemetry-R31\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "network_instance_protocols_bgp_admin_state{target=\"clab-telemetry-R32\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "network_instance_protocols_bgp_neighbor_session_state{target=\"clab-telemetry-R22\", neighbor_peer_address=\"20.20.12.1\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "network_instance_protocols_bgp_neighbor_session_state{target=\"clab-telemetry-R21\", neighbor_peer_address=\"20.20.12.2\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "network_instance_protocols_bgp_neighbor_session_state{target=\"clab-telemetry-R21\", neighbor_peer_address=\"12.12.12.1\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "network_instance_protocols_bgp_neighbor_session_state{target=\"clab-telemetry-R11\", neighbor_peer_address=\"12.12.12.2\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "network_instance_protocols_bgp_neighbor_session_state{target=\"clab-telemetry-R32\", neighbor_peer_address=\"30.30.12.1\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "network_instance_protocols_bgp_neighbor_session_state{target=\"clab-telemetry-R31\", neighbor_peer_address=\"30.30.12.2\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "network_instance_protocols_bgp_neighbor_session_state{target=\"clab-telemetry-R31\", neighbor_peer_address=\"13.13.13.1\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "network_instance_protocols_bgp_neighbor_session_state{target=\"clab-telemetry-R12\", neighbor_peer_address=\"13.13.13.2\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "network_instance_protocols_bgp_group_admin_state{target=\"clab-telemetry-R21\", group_group_name=\"iBGP-AS2\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "network_instance_protocols_bgp_group_admin_state{target=\"clab-telemetry-R21\", group_group_name=\"eBGP-AS-12\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "network_instance_protocols_bgp_group_admin_state{target=\"clab-telemetry-R31\", group_group_name=\"iBGP-AS3\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "network_instance_protocols_bgp_group_admin_state{target=\"clab-telemetry-R32\", group_group_name=\"iBGP-AS3\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}