{
 "title": "New dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "in/out packets deriv [interval]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "deriv(interface_subinterface_statistics_out_packets{target=\"clab-telemetry-R14\", interface_name=\"ethernet-1/49\"}[$__interval])",
     "legendFormat": "__auto"
    },
    {
     "expr": "deriv(interface_subinterface_statistics_in_packets{target=\"clab-telemetry-R14\", interface_name=\"ethernet-1/49\"}[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "in/out packets",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 0 },
   "targets": [
    {
     "expr": "interface_subinterface_statistics_out_packets{target=\"clab-telemetry-R14\", interface_name=\"ethernet-1/49\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "interface_subinterface_statistics_in_packets{target=\"clab-telemetry-R14\", interface_name=\"ethernet-1/49\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "in/out packets rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(interface_subinterface_statistics_out_packets{target=\"clab-telemetry-R14\", interface_name=\"ethernet-1/49\"}[$__rate_interval])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(interface_subinterface_statistics_in_packets{target=\"clab-telemetry-R14\", interface_name=\"ethernet-1/49\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "in/out packets rate rounded",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 10, "y": 8 },
   "targets": [
    {
     "expr": "round(rate(interface_subinterface_statistics_out_packets{target=\"clab-telemetry-R14\", interface_name=\"ethernet-1/49\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "round(rate(interface_subinterface_statistics_in_packets{target=\"clab-telemetry-R14\", interface_name=\"ethernet-1/49\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "in/out packets",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "interface_subinterface_statistics_out_packets{target=\"clab-telemetry-R14\", interface_name=\"ethernet-1/49\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "interface_subinterface_statistics_in_packets{target=\"clab-telemetry-R14\", interface_name=\"ethernet-1/49\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "in/out packets irate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 10, "y": 15 },
   "targets": [
    {
     "expr": "irate(interface_subinterface_statistics_out_packets{target=\"clab-telemetry-R14\", interface_name=\"ethernet-1/49\"}[$__rate_interval])",
     "legendFormat": "__auto"
    },
    {
     "expr": "irate(interface_subinterface_statistics_in_packets{target=\"clab-telemetry-R14\", interface_name=\"ethernet-1/49\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}