{
 "title": "system",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "in packets",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "avg by(target) (sum by(target) (rate(interface_subinterface_statistics_in_packets{interface_name!=\"mgmt0\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "out packets",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "avg by(target) (sum by(target) (rate(interface_subinterface_statistics_out_packets{interface_name!=\"mgmt0\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 8 },
   "targets": [
    {
     "expr": "platform_control_cpu_total_instant{subscription_name=\"sub-system\"}",
     "legendFormat": "{{target}}"
    }
   ]
  }
 ]
}